### ISSUE TITLE
Attributes aren't inherited by subclasses

### ISSUE THREAD

**Issue by rhunwicks** [bmihelac/django-import-export#140]
I have a base model and a set of subclasses of the model. As you might expect, when I create the import/export ModelResources for those subclass models there is a lot of duplicated code related to the base model. I'd like to move that code into a base ModelResource and then subclass it. For example:

```python
class BaseResource(resources.ModelResource):
    parent_field = fields.Field(attribute='parent__base_field', readonly=True)

    class Meta:
        model = BaseModel
        use_transactions = True 
        skip_unchanged = True
        report_skipped = True
        abstract = True

class SubclassResource(BaseResource)

    class Meta:
        model = SubclassModel
```

Unfortunately, when I tried this the `fields.Field` attributes on the parent `BaseResource` aren't inherited on the `SubclassResource`. I think this is because the `DeclarativeMetaclass.__new__()` only copies attributes passed in directly and doesn't loop through `bases` and add them from there. However, I'm not familiar enough with metaclass programming or django-import-export to know the best way to fix it.

**Comment by rhunwicks** [comment]
I'm working on a replacement PR to solve this issue, which doesn't have any of the other stuff. It also allows Meta attributes to be inherited so that `skip_unchanged` etc can be set on a parent class, as well as fields.

One thing I'd like you to consider... what do we do with unauthorized Meta attributes?

For example, I have a custom `Resource` where I did:

```python
class BaseResource(resources.ModelResource):
    parent_field = fields.Field(attribute='parent__base_field', readonly=True)

    class Meta:
        model = BaseModel
        insert_only = True  # This is a custom attribute
```

If I change the way the `_meta` is setup, what should I do with attributes that exist in the subclasses, but which aren't official - i.e. which don't exist in `ResourceOptions`.

I see three approaches:

1. We discard any unofficial attributes, possibly issuing a warning. This might break existing code (like mine) but would be consistent with how Django deals with additional attributes on `Meta` classes in models.
1. We discard any unofficial attributes on parent classes but allow them on the final class. This would be an intermediate solution, where we exert more control over `Meta` but don't break any existing code, because it can't be relying on inheritance yet. The documentation would need to be clear.
1. We continue to allow custom attributes in `Meta` and faithfully copy them to the subclasses.

Thoughts?

**Comment by bmihelac** [comment]
@rhunwicks I am not sure. Would like to follow Django practices to reduce possibility of surprises. How does other libraries handle this?

**Comment by rhunwicks** [comment]
I'm not aware of any other libraries that are doing Meta inheritance. I would lean towards copying the attributes because:

* it will mean existing code still works
* I have found the Django models approach inconvenient anyway
* we don't have much functionality in our metaclass, which is I think the justification for Django models removing them - they don't want to take the chance a user-supplied attribute breaks something because the metaclass methods don't know about it.

**Comment by halfnibble** [comment]
I would like to reopen this issue. The fix seems to only apply to a normal `Resource` and not a `ModelResource`.

**Comment by halfnibble** [comment]
Well....maybe there is something wrong with my code. I just switched to using a regular `Resource` and am experiencing the same problem. Which is odd because my code looks like it mirrors the test case *exactly.* And that test case is passing.

**Comment by halfnibble** [comment]
Please disregard my previous comments. I had somehow managed to install my packages using an old requirements.txt file. Everything works as expected. Thanks.
