### ISSUE TITLE
Exporting ForeignKey

### ISSUE THREAD

**Issue by teshomem** [bmihelac/django-import-export#197]
I have models:

class Project(models.Model):
    project = models.CharField(max_length=255)
def __str__(self):
        return self.project

class Customer(models.Model):
    project = models.ForeignKey(Project)
    customer = models.CharField(max_length=255, unique=True)
def __str__(self):
        return self.customer

When I export Customer table, I get project_id value of the project field in the Project table. Is there a way we can export the project value from Project table instead of its ID.

Thanks :-)

teshomem

**Comment by bmihelac** [comment]
sure, use ``project__project`` as field, see docs.

**Comment by teshomem** [comment]
Thanks :-)
