### ISSUE TITLE
Setting the mimetype in django 1.7 does not work

### ISSUE THREAD

**Issue by vladlep** [bmihelac/django-import-export#198]
Hi,

When i try to export i get this error:
  __init__() got an unexpected keyword argument 'mimetype'
    
    in django-import-export/django-import-export/import_export/admin.py in export_action
    line: 285     mimetype='application/octet-stream', 

I think that the error is generated by the fact that i use django 1.7.2 and mimetype was changed to content_type.

Thanks.

**Comment by bmihelac** [comment]
which version?

I thought this was fixed with:
https://github.com/bmihelac/django-import-export/commit/0dfb4b9d8288bf47e56465f9269f96f56aea5c55

**Comment by vladlep** [comment]
you are right, it is fixed.  I made a mistake when updating my requirements. Sorry.
