### ISSUE TITLE
Matching Excel column names to database fields

### ISSUE THREAD

**Issue by jtiki** [bmihelac/django-import-export#201]
I was wondering if there was a way to match column's in an Excel sheet to a database field with a different name. For example if my models.py looks like this:
```python
...
class Talk(models.Model):
    name = models.CharField(max_length=100)
    talk_day = models.DateField()
    time_start = models.TimeField()
    time_end = models.TimeField()
    conference = models.ForeignKey(Conference, related_name="talks")
    users = models.ManyToManyField(User, related_name="talks")
...
```
Could I match an excel sheet with a column name "Day of Talk" to 'talk_day'? I tried setting up a resource like so:
admin.py
```python
class TalkResource(resources.ModelResource):
    talk_day = fields.Field(attribute="day of talk",
                            column_name="day of talk",
                            widget=DateWidget)

    class Meta:
        model = Talk
```
Then importing the following excel sheet:
|-------------------------------------------------------------------------------------------------|
| id | name          | day of talk   | time_start | time_end | conference | users |
|-------------------------------------------------------------------------------------------------|
|    | Some Talk  | 1/1/15      |  ...                | ...             |   1               |           |
|-------------------------------------------------------------------------------------------------|

But when the preview shows up all of the fields are filled in except 'talk_day'.

**Comment by bmihelac** [comment]
Just remove ``attribute="day of talk"``  from field definition

**Comment by jtiki** [comment]
I changed the resource to the following:
```python
class TalkResource(resources.ModelResource):
        talk_day = fields.Field(column_name="day of talk",
                                            widget=DateWidget)

        class Meta:
            model = Talk
```
and tried to import the same excel sheet but get this preview:
![screen shot 2015-01-30 at 8 06 40 am](https://cloud.githubusercontent.com/assets/1173792/5976038/5160bb34-a857-11e4-9490-da51f9c8659a.png)

**Comment by bmihelac** [comment]
it should work, there are test cases and I use this very often:

https://github.com/bmihelac/django-import-export/blob/master/tests/core/tests/resources_tests.py#L63-L68

**Comment by jtiki** [comment]
Sorry, unfortunately I'm still not able to get it working. Could it possibly be that I'm using Python 3.4.2?
I'm also going to paste my model.py and admin.py to make sure I didn't mess anything up:
admin.py
```python
from django.contrib import admin
from .models import Conference
from .models import Talk

from import_export import resources
from import_export import fields
from import_export.admin import ImportExportModelAdmin
from import_export.widgets import DateWidget


class ConferenceResource(resources.ModelResource):
    class Meta:
        model = Conference


class TalkResource(resources.ModelResource):
    talk_day = fields.Field(column_name="day of talk")

    class Meta:
        model = Talk


class ConferenceAdmin(ImportExportModelAdmin):
    resource = ConferenceResource


class TalkAdmin(ImportExportModelAdmin):
    filter_horizontal = ('users',)
    resource = TalkResource


admin.site.register(Conference, ConferenceAdmin)
admin.site.register(Talk, TalkAdmin)
```
models.py
```python
from django.db import models
from django.contrib.auth.models import User


class Conference(models.Model):
    name = models.CharField(max_length=100)


class Talk(models.Model):
    name = models.CharField(max_length=100)
    talk_day = models.DateField()
    time_start = models.TimeField()
    time_end = models.TimeField()
    conference = models.ForeignKey(Conference, related_name="talks")
    users = models.ManyToManyField(User, related_name="talks")

````

**Comment by bmihelac** [comment]
@jtiki can you try to export one row from admin and then import this file back in?

**Comment by jtiki** [comment]
@bmihelac Absolutely, and thank you for the help!

![screen shot 2015-01-30 at 8 35 16 am](https://cloud.githubusercontent.com/assets/1173792/5976373/066f5c3a-a85b-11e4-9550-317e7a66314f.png)

**Comment by bmihelac** [comment]
please try this:

    talk_day = fields.Field(attribute='talk_day ', column_name="day of talk")

**Comment by jtiki** [comment]
admin.py
```python
...
class TalkResource(resources.ModelResource):
    talk_day = fields.Field(attribute='talk_day ', column_name="day of talk")

    class Meta:
        model = Talk
...
````
Same result:
![screen shot 2015-01-30 at 8 40 44 am](https://cloud.githubusercontent.com/assets/1173792/5976434/bc747b14-a85b-11e4-95cd-dd163c9c9f08.png)

**Comment by bmihelac** [comment]
See:

https://github.com/bmihelac/django-import-export/compare/demo-201?expand=1

It should be ``resource_class`` and not ``resource`` in your admin....

**Comment by jtiki** [comment]
@bmihelac Ah sorry that was a stupid mistake on my part.

**Comment by bmihelac** [comment]
no problem, glad it works for you :)

**Comment by jtiki** [comment]
One other quick question, now that the import is working, it is importing the date as a decimal, so I added
```python 
class TalkResource(resources.ModelResource):
    talk_day = fields.Field(attribute='talk_day', column_name="day of talk",
                            widget=DateWidget())
````
That which is producing this error:

Line number: 1 - Column 'day of talk': Enter a valid date.
Traceback (most recent call last):
File "/Users/jlspencergarlitz/Sites/earnyourcredit/venv/lib/python3.4/site-packages/import_export/fields.py", line 57, in clean
value = self.widget.clean(value)
File "/Users/jlspencergarlitz/Sites/earnyourcredit/venv/lib/python3.4/site-packages/import_export/widgets.py", line 119, in clean
raise ValueError("Enter a valid date.")
ValueError: Enter a valid date.

**Comment by bmihelac** [comment]
You would need widget for excel format, this is straight from my custom project....

    import tablib

    class ExcelDateWidget(widgets.CharWidget):
        """
        Excel date widget.

            * ``datemode``
        """

        def __init__(self, datemode, *args, **kwargs):
            self.datemode = datemode
            super(ExcelDateWidget, self).__init__(*args, **kwargs)

        def render(self, value):
            if value is None:
                return None
            return tablib.compat.xlrd.xldate.xldate_from_date_tuple(
                value.timetuple()[:3], self.datemode)

        def clean(self, value):
            if not value:
                return None
            tup = tablib.compat.xlrd.xldate.xldate_as_tuple(value, self.datemode)
            return date(*tup[:3])

**Comment by bmihelac** [comment]
This should be added to django-import-export, so if you are up to for writing few tests, adding documentation I will gladly accept pull request

**Comment by jtiki** [comment]
Absolutely.

**Comment by jtiki** [comment]
I'm working on that patch, but the ExcelDateWidget is going to need another bit of information available in the widget for best results.

Right now ExcelDataWidget requires one parameter which is datemode. datemode is used to differentiate Mac Excel from Window's Excel, and the dates are off by 1400~ days. The only way to guarantee the correct date is to use to have something like this:
```python
class XLS(TablibFormat):
    ...
    def create_dataset(self, in_stream):
        ...
        xls_book = xlrd.open_workbook(file_contents=in_stream)
        dataset = tablib.Dataset()
        sheet = xls_book.sheets()[0]
        dataset.datemode = xls_book.datemode
        ...
````
And unless that can datamode can be accessed from the widget we would just have to guess what mode to put the widget in each time.
