### ISSUE TITLE
Exporting large datasets - server timeouts

### ISSUE THREAD

**Issue by marksweb** [bmihelac/django-import-export#206]
I'm having trouble with server timeouts due to the size of some exports & wondered if it's possible to integrate the export function with the StreamingHttpResponse?

I put this up on SO because I can't see anything in the app or in the issues that might help with this. Any idea if it's possible? I've not used a streaming response before but I gather it requires something it can iterate over.
http://stackoverflow.com/questions/28383358/streaming-a-response-with-django-import-export

**Comment by bmihelac** [comment]
sorry but I think it would not be possible to create stream of export from tablib which django-import-export uses.

**Comment by marksweb** [comment]
Ok thanks. I might have to investigate making something of my own then :)

**Comment by rhunwicks** [comment]
I do this with Django Rest Framework (with the CSV and XML plugins) and a custom class that returns a generator

**Comment by pySilver** [comment]
@rhunwicks have you tried this approach with large datasets (at least 1M items)?

**Comment by rhunwicks** [comment]
No, the largest I have done is about 300,000 items, but the records are very large and the serialization is computationally intensive, so the process takes a long time to run - many minutes - and the downloaded data file is also large 425MB.

**Comment by jangeador** [comment]
@rhunwicks Do you have any sample code that you could share about the custom class that you described?

**Comment by salientroot** [comment]
i think this issue didn't fix still and who can i help me with that?

**Comment by EmadMokhtar** [comment]
I managed to hack it into my resource class.

```python
    def export_as_generator(self, queryset=None, *args, **kwargs):
        self.before_export(queryset, *args, **kwargs)
        if queryset is None:
            queryset = self.get_queryset()
        headers = self.get_export_headers()
        data = tablib.Dataset(headers=headers)
        # Return headers
        yield data.csv

        if isinstance(queryset, QuerySet):
            # Iterate without the queryset cache, to avoid wasting memory when
            # exporting large datasets.
            iterable = queryset.iterator()
        else:
            iterable = queryset
        for obj in iterable:
            # Return subset of the data (one row)
            # This is a simple implementation to fix the tablib library which is missing returning the data as
            # generator
            data = tablib.Dataset()
            data.append(self.export_resource(obj))
            yield data.csv

        self.after_export(queryset, data, *args, **kwargs)

        yield
```

Then in the view, I call this method like that

```python
dataset = self.resource_class().export_as_generator()
response = StreamingHttpResponse(dataset, content_type="csv")
```


It needs some enhancements (like appending page of the queryset instead of one row). I can create a PR.

**Comment by joshgeller** [comment]
> ```python
> content_type="csv"
> ```

Thanks for this solution! Did you ever add the enhancements you mentioned?

**Comment by joshgeller** [comment]
> I managed to hack it into my resource class.
> 
> ```python
>     def export_as_generator(self, queryset=None, *args, **kwargs):
>         self.before_export(queryset, *args, **kwargs)
>         if queryset is None:
>             queryset = self.get_queryset()
>         headers = self.get_export_headers()
>         data = tablib.Dataset(headers=headers)
>         # Return headers
>         yield data.csv
> 
>         if isinstance(queryset, QuerySet):
>             # Iterate without the queryset cache, to avoid wasting memory when
>             # exporting large datasets.
>             iterable = queryset.iterator()
>         else:
>             iterable = queryset
>         for obj in iterable:
>             # Return subset of the data (one row)
>             # This is a simple implementation to fix the tablib library which is missing returning the data as
>             # generator
>             data = tablib.Dataset()
>             data.append(self.export_resource(obj))
>             yield data.csv
> 
>         self.after_export(queryset, data, *args, **kwargs)
> 
>         yield
> ```
> 
> Then in the view, I call this method like that
> 
> ```python
> dataset = self.resource_class().export_as_generator()
> response = StreamingHttpResponse(dataset, content_type="csv")
> ```
> 
> It needs some enhancements (like appending page of the queryset instead of one row). I can create a PR.

Thanks for this solution! Did you ever add the enhancements you mentioned?

**Comment by deanmcginndm** [comment]
Hey, stumbled upon this post and wanted to expand on it a little better as the solution wasnt fully functioning in terms of only returning the csv data, and also, perhaps I misunderstand their purpose, but I also believe there are 3 yield statements, where there could be one. This causes the code to output bad JSON data.

Please see me below proposed update to the solution above:

    
    def export(self, queryset=None, *args, **kwargs):
        self.before_export(queryset, *args, **kwargs)

        # get the file extension, so that we can getattr the dataset on the yield statement
        # we do this as otherwise we will only ever export CSV files
        file_extension = kwargs.get('file_format').get_extension()
        if queryset is None:
            queryset = self.get_queryset()
        headers = self.get_export_headers()
        data = tablib.Dataset(headers=headers)
        # remove unnecessary yielding of the header data
        # yield getattr(data, file_extension)

        if isinstance(queryset, QuerySet):
            # Iterate without the queryset cache, to avoid wasting memory when
            # exporting large datasets.
            iterable = queryset.iterator()
        else:
            iterable = queryset

        for obj in iterable:
            # Return subset of the data (one row)
            # This is a simple implementation to fix the tablib library which is missing returning the data as
            # generator
            data.append(self.export_resource(obj))
            if getattr(data, file_extension):
                yield getattr(data, file_extension)

        self.after_export(queryset, data, *args, **kwargs)

        # removed a dangling yield statement
        # yield

This code is overriden from the export function of `ModelResource`, there is also another thing required, as alluded to in the solution post. That being to change the way we return the response, instead making it a Streaming Response instead.

```
class UserAdmin(ExportMixin, auth.admin.UserAdmin):
    # note below, we override the template with a template placed in the app template directory
    change_list_template = 'user_export_streamed.html'
    resource_class = UserResource
    list_display = auth.admin.UserAdmin.list_display + ('date_joined',)
    inlines = [
        UserProfileInline,
    ]

    def approve(self, request, queryset):
        queryset.update(is_active=True)
        self.message_user(message='Successfully approved {} user(s)'.format(queryset.count()), request=request)

    approve.short_description = "Approve selected users"

    def __init__(self, *args, **kwargs):

        if getattr(settings, 'ACCOUNT_ACTIVATION', 'self') == 'self':
            self.actions += ['approve']

        super().__init__(*args, **kwargs)
    
    # note below, we override the get_urls() function to add the export_streamed/ link and specify the streaming function
    # as its callback
    def get_urls(self):
        urls = super().get_urls()
        my_urls = [
            path('export_streamed/', self.export_streamed),
        ]
        return my_urls + urls
    
    # custom function which is written as specified by the ExportActionMixin and combined with
    # django documentation about how to add custom buttons onto the admin pages
    def export_streamed(self, request, *args, **kwargs):
        if not self.has_export_permission(request):
            raise PermissionDenied

        formats = self.get_export_formats()
        form = ExportForm(formats, request.POST or None)
        if form.is_valid():
            file_format = formats[
                int(form.cleaned_data['file_format'])
            ]()

            queryset = self.get_export_queryset(request)
            dataset = self.resource_class().export(file_format=file_format)
           
            # notice the small detail changing it to a streaming response here
            response = StreamingHttpResponse(dataset, content_type=file_format)
            response['Content-Disposition'] = 'attachment; filename="%s"' % (
                self.get_export_filename(request, queryset, file_format),
            )

            post_export.send(sender=None, model=self.model)
            return response

        context = self.get_export_context_data()

        context.update(self.admin_site.each_context(request))

        context['title'] = _("Export")
        context['form'] = form
        context['opts'] = self.model._meta
        request.current_app = self.admin_site.name
        return TemplateResponse(request, [self.export_template_name],
                                context)
```

**Comment by gioy** [comment]
@EmadMokhtar this works fine with csv, but it doesn't work with excel (xlsx). When I open the file, only the last (data) row is present; there's not even the header row. Seems like data gets overriden instead of appended. I'm using your exact code with the only difference of `yield data.csv` that I changed to `yield data.xlsx`

In my view I have:

```
dataset = resource.export_as_generator()
response = StreamingHttpResponse(
    dataset,
    content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
)

return response
```

Any thoughts?
