### ISSUE TITLE
import error, guess  due to "models.AutoField(primary_key=True"

### ISSUE THREAD

**Issue by mingissb** [bmihelac/django-import-export#211]
Thanks, this is turely a helpful app.
But when I do import.  some errors happen. here the error report
"""
Errors

Line number: 1 - u'id'
Traceback (most recent call last):
File "C:\Python27\lib\site-packages\import_export\resources.py", line 323, in import_data
instance, new = self.get_or_init_instance(instance_loader, row)
File "C:\Python27\lib\site-packages\import_export\resources.py", line 154, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
KeyError: u'id'

Line number: 2 - u'id'
Traceback (most recent call last):
File "C:\Python27\lib\site-packages\import_export\resources.py", line 323, in import_data
instance, new = self.get_or_init_instance(instance_loader, row)
File "C:\Python27\lib\site-packages\import_export\resources.py", line 154, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
KeyError: u'id'
"""
In my models , have PK field: 
    class FacilityInfo(models.Model):
         facility_id = models.AutoField(primary_key=True)
Is this the reason that errors comeup?
How do I fix it ?
Thank you for help
PS: export is OK.

**Comment by jsma** [comment]
There's nothing wrong with your model or id field. The problem is with django-import-export. Apparently django-import-export requires you to have a column with a header 'id' in your import file (xls, csv, etc.) but you have to leave the values in this column blank if you want it to create new records in the database. There are several other related tickets such as #59, #150, #92, #174 and perhaps others.

This has obviously tripped up plenty of users since it is a very odd and undocumented workflow (there is no mention of this in the official docs, just in comments on issues). Usually when you are importing data you are trying to get new data into the database rather than update existing records. django-import-export should be fixed for this common use case.

**Comment by bmihelac** [comment]
There is some documentation that describes import flow and loading model instances:

https://django-import-export.readthedocs.org/en/latest/import_workflow.html
https://django-import-export.readthedocs.org/en/latest/api_instance_loaders.html

Please see ``get_or_init_instance`` description in first doc. By default it calls instance loader to load instance if it already exists (and it does that by looking for ``import_id_fields`` in import document). If you always want to import new data just override and return ``False`` in ``get_instance``.

Pull requests that will improve documentation on this are certainly welcome :)

**Comment by mingissb** [comment]
Hi bmlhelac,
I'm stilling trying import.
"If you always want to import new data just override and return False in get_instance."
I didn't get the point? What should I do?

**Comment by ahmedjawed01** [comment]
you can override it as

# to create a new instance
def get_instance(self, instance_loader, row):
        return False

# your custom save
    def save_instance(self, instance, real_dry_run):
        if not real_dry_run:
                try:
                    obj = YourModel.objects.get(some_val=instance.some_val)
                    # extra logic if object already exist
                except NFCTag.DoesNotExist:
                    # create new object
                    obj = YourModel(some_val=instance.some_val)
                    obj.save()

    def before_import(self, dataset, dry_run):

        if dataset.headers:
            dataset.headers = [str(header).lower().strip() for header in dataset.headers]

## if id column not in headers in your file
        if 'id' not in dataset.headers:
            dataset.headers.append('id')

**Comment by mingissb** [comment]
Sorry, I'm new in coding.
In my mind, the step to import is:
    1. Export a file as a base template
    2. Use the base template and add data in to base template, keep the file structure.
    3. Then import the template
I thought this should be the standard easy way to import data.
Would it work? 
I thought change template will be more ease than change code.
So what should I do?
Please help

**Comment by ahmedjawed01** [comment]
yes its an easy way and work like a charm, unless you want to add some new column in file, or make some customization, then you'll have to do it through overriding the code.

**Comment by mingissb** [comment]
Thank you.
It worked after add ''import_id_fields" .

**Comment by diptipsawant** [comment]
I used "ipmport_id_fields" but still I am getting an error. 
Please, help me. Also I put code into my admin.py which is suggested by @ahmedjawed01
from import_export.admin import ImportExportMixin, ImportExportModelAdmin
from import_export import resources
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin
from django.contrib.auth.models import Group
from django.contrib.sites.models import Site
from django.utils.translation import ugettext as _
from django.db import models
from django.forms import TextInput, Textarea
from rest_framework.authtoken.models import Token

from fx1_user.forms import UserChangeForm, UserRegistrationForm
from fx1_user.models import CustomUser


def move_to_paid(modeladmin, request, queryset):
    for user in queryset:
        CustomUser.objects.move_user_to_paid(user)
move_to_paid.short_description = _("Move selected users to paid")


def move_to_free(modeladmin, request, queryset):
    for user in queryset:
        CustomUser.objects.move_user_to_free(user)
move_to_free.short_description = _("Move selected users to free")

class UserResource(resources.ModelResource):
    class Meta:
        model = CustomUser        
        import_id_fields = ['id',]
        exclude = ('id', )
        fields = ('email','first_name','last_name','contact_number','is_subscribed')        
        def get_instance(self, instance_loader, row):
            return False
        def save_instance(self, instance, real_dry_run):
            if not real_dry_run:
                try:
                    obj = CustomUser.objects.get(some_val=instance.first_name)
                    # extra logic if object already exist
                except NFCTag.DoesNotExist:
                    # create new object
                    obj = CustomUser(some_val=instance.first_name)
                    obj.save()
        def before_import(self, dataset, dry_run):
            if dataset.headers:
                dataset.headers = [str(header).lower().strip() for header in dataset.headers]
   

class CustomUserAdmin(ImportExportMixin,UserAdmin):
    resource_class = UserResource
    # The forms to add and change user instances
    form = UserChangeForm
    add_form = UserRegistrationForm
    actions = [move_to_free, move_to_paid]

    # The fields to be used in displaying the User model.
    # These override the definitions on the base UserAdmin
    # that reference specific fields on auth.User.
    list_display = ('email', 'created', 'is_admin', 'is_subscribed','special_user')
    list_filter = ('is_admin',)
    readonly_fields = (
        'created',
        'last_login',
        'owner',
    )
    fieldsets = (
        (None, {'fields': ('email', 'password',)}),
        (_('Permissions'), {'fields': ('is_admin', 'is_superuser', 'is_subscribed','special_user')}),
        (_('Important dates'), {'fields': ('last_login', 'created',)}),
        (_('Profile'), {'fields': ('profile_picture',
                                   'first_name',
                                   'last_name',
                                   'contact_number',
                                   'referral',
                                   'owner',)}),
        (_('Subscription'), {'fields': ('subscription_type',
                                        'subscription_start',
                                        'subscription_end',
                                        'subscription_ongoing',)}),
    )
    formfield_overrides = {
        models.CharField: {'widget': TextInput(attrs={'size': '20'})},
        models.TextField: {'widget': Textarea(attrs={'rows': 4, 'cols': 40})},
        }
    add_fieldsets = (
        (None, {
            'classes': ('wide',),
            'fields': (
                'email', 'password1', 'password2', 'subscription_type'
            )
        }),
    )
    search_fields = ('email',)
    ordering = ('email',)
    filter_horizontal = ()

# Now register the new UserAdmin...
admin.site.unregister(Token)
admin.site.register(CustomUser, CustomUserAdmin)

**Comment by ahmedjawed01** [comment]
please use this in before_import copy my code as is

if dataset.headers:
        dataset.headers = [str(header).lower().strip() for header in dataset.headers]
#if you already have a id column in your file with values for this column then don't use below code
if 'id' not in dataset.headers:
        dataset.headers.append('id')

**Comment by diptipsawant** [comment]
hello ahmedjawed01,
yes I used removed that append('id') code, because I added id column in dataset of csv file.  but still getting an error. could you check my code , please? its an admin.py. is that code location correct under class UserResource which is created for imoprt/export.
