### ISSUE TITLE
admin.site.site_header not being honored in django 1.7

### ISSUE THREAD

**Issue by abcooley** [bmihelac/django-import-export#213]
Hi when using django 1.7 and the new admin.site.site_header option import-export reverts to the default site_header value of Django Site Admin instead of the customized variable.
![screen shot 2015-02-22 at 7 04 49 pm](https://cloud.githubusercontent.com/assets/11152878/6321568/5d5b1eee-bac6-11e4-8837-1ee6c30f980b.png)
![screen shot 2015-02-22 at 7 04 53 pm](https://cloud.githubusercontent.com/assets/11152878/6321567/5d5818ca-bac6-11e4-81f5-d7dff6805c71.png)

**Comment by bmihelac** [comment]
PR welcome :)
