### ISSUE TITLE
The easy step to import new data from the file exported

### ISSUE THREAD

**Issue by mingissb** [bmihelac/django-import-export#225]
Sorry, I'm new in coding.
In my mind, the step to import is:
1. Export a file as a base template
2. Use the base template and add data in to base template, keep the file structure.
3. Then import the template
I thought this should be the standard easy way to import data.
Would it work? 
I thought change template will be more easy than change code.
So what should I do?
Please help

Below is the my major problem:
Thanks, this is turely a helpful app.
But when I do import. some errors happen. here the error report
"""
Errors

Line number: 1 - u'id'
Traceback (most recent call last):
File "C:\Python27\lib\site-packages\import_export\resources.py", line 323, in import_data
instance, new = self.get_or_init_instance(instance_loader, row)
File "C:\Python27\lib\site-packages\import_export\resources.py", line 154, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
KeyError: u'id'

Line number: 2 - u'id'
Traceback (most recent call last):
File "C:\Python27\lib\site-packages\import_export\resources.py", line 323, in import_data
instance, new = self.get_or_init_instance(instance_loader, row)
File "C:\Python27\lib\site-packages\import_export\resources.py", line 154, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
KeyError: u'id'
"""
In my models , have PK field: 
class FacilityInfo(models.Model):
facility_id = models.AutoField(primary_key=True)
Is this the reason that errors comeup?
How do I fix it ?
Thank you for help
PS: export is OK.

**Comment by manelclos** [comment]
Hi @mingissb,

There is an ''import_id_fields" option in the Resource class that you can use to: "Control which object fields will be used to identify existing instances"

Have you tried that?

It looks this information is not picked up automatically from primary_key setting in the Model.

**Comment by mingissb** [comment]
Thank you.
It worked after 'import_id_fields"

**Comment by mingissb** [comment]
Thank you.
It worked after add ''import_id_fields" .
