### ISSUE TITLE
DataError: integer out of range

### ISSUE THREAD

**Issue by leosquared** [bmihelac/django-import-export#252]
I'm using [Heroku Postgres](https://elements.heroku.com/addons/heroku-postgresql) and Django 1.8. When using this locally with *sqlite3*, it works with no issues. However, when working with Postgres, the file loads successfully up to the *Preview* step, but then fails with the error: 

`DataError: integer out of range`
from this line
`/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py in execute, line 64`

I've tried this with both an update (with a primary key) and as new records (with a primary key column but left blank) and both generate the same issue. Any ideas?

**Comment by MSadeghzadehG** [comment]
I have the same issue. did you solve this?

**Comment by MSadeghzadehG** [comment]
I think found the problem. It seems in sqlite3 id field maximum number is bigger than postgres. my id numbers are big and it doesn't make problem in sqlite3; but according to [Posgresql documentation,](http://www.postgresqltutorial.com/postgresql-identity-column/) id fields type can be INT and this cause overflow and DataError. 
and about the solution, I changed my id numbers but I think changing id field type to BIGINT can be effective.

**Comment by Singh-Sg** [comment]
I was getting this error when I tried to alter a decimal field to integer.  I  changed to big integerfield and  it worked well
